# Generated by Django 5.2.2 on 2025-06-11 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PapersModel_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='papers/')),
                ('title', models.CharField(max_length=200)),
                ('article', models.TextField()),
                ('reference', models.CharField(choices=[('0', 'AI'), ('1', 'Computer'), ('2', 'Marketing'), ('3', 'Product and consumption'), ('4', 'Shopping'), ('5', 'Brand')], max_length=30)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_link', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'papers_en',
                'unique_together': {('author', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PapersModel_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='papers/')),
                ('title', models.CharField(max_length=200)),
                ('article', models.TextField()),
                ('reference', models.CharField(choices=[('0', 'AI'), ('1', 'Computer'), ('2', 'Marketing'), ('3', 'Product and consumption'), ('4', 'Shopping'), ('5', 'Brand')], max_length=30)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_link', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'papers_ru',
                'unique_together': {('author', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PapersModel_UZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='papers/')),
                ('title', models.CharField(max_length=200)),
                ('article', models.TextField()),
                ('reference', models.CharField(choices=[('0', 'AI'), ('1', 'Computer'), ('2', 'Marketing'), ('3', 'Product and consumption'), ('4', 'Shopping'), ('5', 'Brand')], max_length=30)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_link', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'papers_uz',
                'unique_together': {('author', 'title')},
            },
        ),
    ]
