# Generated by Django 5.2.2 on 2025-06-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalsModel_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default="'profile pictures'/pic.png", upload_to='journals/')),
                ('title', models.CharField(max_length=200)),
                ('article', models.TextField()),
                ('reference', models.CharField(choices=[('0', 'AI'), ('1', 'Computer'), ('2', 'Marketing'), ('3', 'Product and consumption'), ('4', 'Shopping'), ('5', 'Brand')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalsModel_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default="'profile pictures'/pic.png", upload_to='journals/')),
                ('title', models.CharField(max_length=200)),
                ('article', models.TextField()),
                ('reference', models.CharField(choices=[('0', 'AI'), ('1', 'Computer'), ('2', 'Marketing'), ('3', 'Product and consumption'), ('4', 'Shopping'), ('5', 'Brand')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalsModel_UZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default="'profile pictures'/pic.png", upload_to='journals/')),
                ('title', models.CharField(max_length=200)),
                ('article', models.TextField()),
                ('reference', models.CharField(choices=[('0', 'AI'), ('1', 'Computer'), ('2', 'Marketing'), ('3', 'Product and consumption'), ('4', 'Shopping'), ('5', 'Brand')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_link', models.URLField()),
            ],
        ),
    ]
